"""Add moderation fields and reports

Revision ID: 79f4eb811acd
Revises: 353acd67bf5f
Create Date: 2025-09-25 10:23:53.075229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79f4eb811acd'
down_revision = '353acd67bf5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('handled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_comment_id'), ['comment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_handled'), ['handled'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_reporter_id'), ['reporter_id'], unique=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moderation_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('toxicity_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_visible', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_is_visible'), ['is_visible'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_moderation_status'), ['moderation_status'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moderation_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('toxicity_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_visible', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_posts_is_visible'), ['is_visible'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_moderation_status'), ['moderation_status'], unique=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strikes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mute_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_shadow_banned', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('is_shadow_banned')
        batch_op.drop_column('mute_until')
        batch_op.drop_column('strikes')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_moderation_status'))
        batch_op.drop_index(batch_op.f('ix_posts_is_visible'))
        batch_op.drop_column('is_visible')
        batch_op.drop_column('toxicity_score')
        batch_op.drop_column('moderation_status')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_moderation_status'))
        batch_op.drop_index(batch_op.f('ix_comments_is_visible'))
        batch_op.drop_index(batch_op.f('ix_comments_created_at'))
        batch_op.drop_column('is_visible')
        batch_op.drop_column('toxicity_score')
        batch_op.drop_column('moderation_status')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_reporter_id'))
        batch_op.drop_index(batch_op.f('ix_reports_post_id'))
        batch_op.drop_index(batch_op.f('ix_reports_handled'))
        batch_op.drop_index(batch_op.f('ix_reports_created_at'))
        batch_op.drop_index(batch_op.f('ix_reports_comment_id'))

    op.drop_table('reports')
    # ### end Alembic commands ###
